export {
  type DifferenceKind,
  type DifferenceRange,
  type ByteDiff,
  type OffsetPatchChange,
  type OffsetPatchFile,
  type PatchMetadata,
  diffBytes,
  createOffsetPatch,
  applyOffsetPatch,
  serializeOffsetPatch,
  validateOffsetPatch,
  verifyPatch,
  applyVerifiedPatch,
} from '../../packages/core/src/diff'
