export {
  type BytePatch,
  type RangeOperation,
  type TransformOptions,
  type DocumentTransaction,
  type UnifiedHistoryState,
  createPatch,
  applyPatch,
  transformRange,
  patchesSize,
  appendPatch,
  createEmptyHistory,
  pushTransaction,
  applyUndo,
  applyRedo,
} from '../../packages/core/src/edits'
